### ISSUE TITLE
Please map 'z' and 'x' keys

### ISSUE THREAD

**Issue by EvHaus** [d4l3k/opentetrisarena#1]
Could you please map the `z` key to rotate left and the `x` key to rotate right? Thanks!

**Comment by d4l3k** [comment]
Not sure when I'll get around to this, but PRs are always welcome!

**Comment by EvHaus** [comment]
Wow, thanks for the fast turnaround! You should check out our recruitment page: https://cumul8.com/careers/

We're actively hiring engineers to come work on some really challenging problems. Tetris proficiency is a requirement as well. I could use a challenge :)
